# Generated by Django 6.0.4 on 2026-04-09 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
